### ISSUE TITLE
Timecard events throws exception.

### ISSUE THREAD

**Issue by purvathakkar** [square/connect-java-sdk#57]
``` 
        V1EmployeesApi v1EmployeesApi  = new V1EmployeesApi();
       V1EmployeesApi v1EmployeesApi  = new V1EmployeesApi();
        List<V1TimecardEvent> timeCardEvents = new ArrayList<>();
        for(String id : timeCardIds){
            timeCardEvents.addAll(v1EmployeesApi.listTimecardEvents(id));
        }
```

I have timecard Ids , this used to work with earlier versions. 
I have recently updated SDK. 

Now it gives me this error.

```
java.lang.IllegalStateException: The template variable 'timecard_id' has no value
	at org.glassfish.jersey.client.JerseyWebTarget.getUri(JerseyWebTarget.java:135)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:215)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:60)
	at com.squareup.connect.ApiClient.invokeAPI(ApiClient.java:649)
```

Thank you :)

**Comment by StephenJosey** [comment]
Thanks for letting us know! I'm seeing this error as well, so we'll dig into it and follow-up once we have more information.

**Comment by purvathakkar** [comment]
2.20190313.1  SDK update resolved issue for me. Thank you :)
